### ISSUE TITLE
`kubernaut set-token` fails with a traceback

### ISSUE THREAD

**Issue by exarkun** [datawire/kubernaut#27] opened 2018-01-12 19:14 UTC
I `pip install kubernaut`'ed (on Python 2.7; Ubuntu).  When I got to the set-token step:

```
Traceback (most recent call last):
  File "/home/exarkun/Environments/everything/bin/kubernaut", line 11, in <module>
    sys.exit(cli())
  File "/home/exarkun/Environments/everything/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/exarkun/Environments/everything/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/exarkun/Environments/everything/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/exarkun/Environments/everything/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/exarkun/Environments/everything/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/exarkun/Environments/everything/local/lib/python2.7/site-packages/kubernaut/cli.py", line 137, in wrapper
    return func(*args, **kwargs)
  File "/home/exarkun/Environments/everything/local/lib/python2.7/site-packages/kubernaut/cli.py", line 221, in cli_set_token
    save_config(config)
  File "/home/exarkun/Environments/everything/local/lib/python2.7/site-packages/kubernaut/cli.py", line 99, in save_config
    json.dump(config_data, cf, indent=2)
  File "/usr/lib/python2.7/json/__init__.py", line 190, in dump
    fp.write(chunk)
TypeError: write() argument 1 must be unicode, not str
```

**Comment by alexgervais** [comment] 2018-01-17 18:39
I get the same error. Installed with Python 3.6.4, pip 9.0.1

**Comment by plombardi89** [comment] 2018-01-17 18:42
@alexgervais `kubernaut --version`? This should be fixed in 0.1.40...

**Comment by alexgervais** [comment] 2018-01-17 20:16
It is failing on a fresh install of `kubernaut v0.1.40`

**Comment by plombardi89** [comment] 2018-01-18 16:28
I was unable to reproduce this last night, but I was able to reproduce it this morning with python 3.6.3... digging into it now.

**Closed** 2018-01-18 17:28 UTC
Labels: Bug, CLI

**Comment by plombardi89** [comment] 2018-01-18 18:08
@alexgervais I need to fix GH-28 now to get this one out officially but you can install from source with `pip install -e .` or pointing at the git repo.

**Comment by alexgervais** [comment] 2018-01-18 18:11
@plombardi89 success! Thanks!
