### ISSUE TITLE
kubernaut client doesn't seem to work on circleci macos

### ISSUE THREAD

**Issue by rhs** [datawire/kubernaut#45] opened 2018-11-03 04:20 UTC
chmod +x ./kubernaut
./kubernaut claims delete cluster-distiller-1A7B0AA4-65E3-4717-90C2-E9EA1B8BC5B4
[1707] Error loading Python lib '/var/folders/ms/xg67k5sn16xc7sdr_w3q45840000gn/T/_MEIyD8FYn/.Python': dlopen: dlopen(/var/folders/ms/xg67k5sn16xc7sdr_w3q45840000gn/T/_MEIyD8FYn/.Python, 10): Symbol not found: _futimens
  Referenced from: /var/folders/ms/xg67k5sn16xc7sdr_w3q45840000gn/T/_MEIyD8FYn/.Python (which was built for Mac OS X 10.13)
  Expected in: /usr/lib/libSystem.B.dylib
 in /var/folders/ms/xg67k5sn16xc7sdr_w3q45840000gn/T/_MEIyD8FYn/.Python
make: *** [cluster.knaut] Error 255
Exited with code 2

**Comment by plombardi89** [comment] 2018-11-03 09:33
That's an interesting one... I'm totally unfamiliar with CircleCI. Can you do a bit of probing to figure out the problem?

**Comment by ark3** [comment] 2018-11-03 18:01
That's caused by version issues. I think Circle is on 10.12 and XCode 9. I suggest setting up your Kubernaut MacOS build step (on Travis, right?) to use an older XCode.

**Comment by plombardi89** [comment] 2018-11-03 19:46
Do we need publish Mac binaries for each version of OS X or just use an ancient X Code for some reason?

**Comment by rhs** [comment] 2018-11-04 01:06
I *think* if you just build with an older version that same binary will work on newer versions also.

**Comment by ark3** [comment] 2018-11-04 16:19
The official Python binaries (from python.org) support 10.9 and higher. We can probably do the same. I think one problem might be that we are using PyInstaller with a Homebrew build of Python. Those are not intended to be portable.

**Comment by rhs** [comment] 2018-11-04 19:15
FWIW, I've worked around this by writing a small kubernaut client in go. (Yay gubernaut!)

**Comment by plombardi89** [comment] 2018-11-05 07:59
Appears to be this: https://github.com/pyinstaller/pyinstaller/issues/3418

**Comment by plombardi89** [comment] 2018-11-14 21:07
Fixed in latest release.

**Closed by plombardi89** 2018-11-14 21:07 UTC
